# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc6e8d7b0bdd6ae78b46322a3802b5d72b44d7cf27d76d554dcd901ae5a7065cd808ef64dbb6ae2961c672251818b56928b3cc1257e7cd090cbc8a14c79959ab

test:
  secret_key_base: cfc839b98369087d85cf176dfe62806a53925c076b2eba7da3e7a33d25df32b0954005c0728b27202a29b0188650ee3a15079e19e40e3447c385341b727e0d6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
